# -*- coding: utf-8 -*-
"""C4W2_Assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/https-deeplearning-ai/tensorflow-3-public/blob/main/Course%204%20-%20Generative%20Deep%20Learning/W2/assignment/C4W2_Assignment.ipynb

# Week 2 Assignment: CIFAR-10 Autoencoder

For this week, you will create a convolutional autoencoder for the [CIFAR10](https://www.tensorflow.org/datasets/catalog/cifar10) dataset. You are free to choose the architecture of your autoencoder provided that the output image has the same dimensions as the input image.

After training, your model should meet loss and accuracy requirements when evaluated with the test dataset. You will then download the model and upload it in the classroom for grading.

Let's begin!

***Important:*** *This colab notebook has read-only access so you won't be able to save your changes. If you want to save your work periodically, please click `File -> Save a Copy in Drive` to create a copy in your account, then work from there.*

## Imports
"""

# IMPORTANT: Install grader-compatible versions of these packages.
# You can safely ignore dependency conflicts in the output.
'''
!pip install keras==3.9.0
!pip install tensorflow==2.18
!pip install tf-keras==2.18
!pip install ml-dtypes==0.5.1
'''

import tensorflow as tf
import tensorflow_datasets as tfds

from keras.models import Sequential

"""## Load and prepare the dataset

The [CIFAR 10](https://www.tensorflow.org/datasets/catalog/cifar10) dataset already has train and test splits and you can use those in this exercise. Here are the general steps:

* Load the train/test split from TFDS. Set `as_supervised` to `True` so it will be convenient to use the preprocessing function we provided.
* Normalize the pixel values to the range [0,1], then return `image, image` pairs for training instead of `image, label`. This is because you will check if the output image is successfully regenerated after going through your autoencoder.
* Shuffle and batch the train set. Batch the test set (no need to shuffle).

"""

# preprocessing function
def map_image(image, label):
  image = tf.cast(image, dtype=tf.float32)
  image = image / 255.0

  return image, image # dataset label is not used. replaced with the same image input.

# parameters
BATCH_SIZE = 128
SHUFFLE_BUFFER_SIZE = 1024

### START CODE HERE (Replace instances of `None` with your code) ###

# use tfds.load() to fetch the 'train' split of CIFAR-10
train_dataset = tfds.load ( 'cifar10', as_supervised=True, split="train")

# preprocess the dataset with the `map_image()` function above
train_dataset = train_dataset.map(map_image)

# shuffle and batch the dataset
train_dataset = train_dataset.shuffle(SHUFFLE_BUFFER_SIZE).batch(BATCH_SIZE).repeat()

# use tfds.load() to fetch the 'test' split of CIFAR-10
test_dataset = tfds.load('cifar10', as_supervised=True, split="test")

# preprocess the dataset with the `map_image()` function above
test_dataset = test_dataset.map(map_image)

# batch the dataset
test_dataset =  test_dataset.batch(BATCH_SIZE).repeat()

### END CODE HERE ###

"""## Build the Model

Create the autoencoder model. 
As shown in the lectures, you will want to downsample the image in the encoder layers then upsample it in the decoder path. 
Note that the output layer should be the same dimensions as the original image. 
Your input images will have the shape `(32, 32, 3)`. 
If you deviate from this, your model may not be recognized by the grader and may fail.

We included a few hints to use the Sequential API below but feel free to 
remove it and use the Functional API just like in the ungraded labs 
if you're more comfortable with it. 
Another reason to use the latter is if you want to visualize the encoder output. 
As shown in the ungraded labs, it will be easier to indicate multiple outputs with the Functional API. 
That is not required for this assignment though so you can just stack layers sequentially if you want a simpler solution.
"""

# suggested layers to use. feel free to add or remove as you see fit.
from keras.layers import Conv2D, UpSampling2D, BatchNormalization, ReLU, MaxPool2D, MaxPooling2D

# use the Sequential API (you can remove if you want to use the Functional API)
model = Sequential()

### START CODE HERE ###
# use `model.add()` to add layers to your autoencoder (if using the Sequential API)
#Encoder
model.add(tf.keras.Input(shape=(32,32,3)))

model.add ( Conv2D(filters=64, kernel_size=(3,3) , use_bias=False, padding='same') )
model.add ( BatchNormalization() )
model.add ( ReLU())

model.add ( MaxPooling2D ( ) )

model.add ( Conv2D(filters=128, kernel_size=(3,3) , use_bias=False, padding='same') )
model.add ( BatchNormalization() )
model.add ( ReLU())

model.add ( MaxPooling2D ( ) )

#Bottleneck

model.add ( Conv2D(filters=256, kernel_size=(3,3) , use_bias=False, padding='same') )
model.add ( BatchNormalization() )
model.add ( ReLU())

#Decoder

model.add ( Conv2D(filters=128, kernel_size=(3,3) , use_bias=False, padding='same'))
model.add ( BatchNormalization() )
model.add ( ReLU())

model.add ( UpSampling2D ( ))


model.add ( Conv2D(filters=64, kernel_size=(3,3) , use_bias=False, padding='same'))
model.add ( BatchNormalization() )
model.add ( ReLU())

model.add ( UpSampling2D ( ))

model.add ( Conv2D(filters=3, kernel_size=(3,3) ,  activation='sigmoid', padding='same'))


### END CODE HERE ###

model.summary()

"""## Configure training parameters

We have already provided the optimizer, metrics, and loss in the code below.
"""

# Please do not change the model.compile() parameters
model.compile(optimizer='adam', metrics=['accuracy'], loss='mean_squared_error')

"""## Training

You can now use [model.fit()](https://keras.io/api/models/model_training_apis/#fit-method) to train your model. You will pass in the `train_dataset` and you are free to configure the other parameters. As with any training, you should observe the loss generally going down and the accuracy going up at each epoch. If not, please revisit the previous sections to find possible bugs.

*Note: If you get a `dataset length is infinite` error. Please check how you defined `train_dataset`. You might have included a [method that repeats the dataset indefinitely](https://www.tensorflow.org/api_docs/python/tf/data/Dataset#repeat).*
"""

### START CODE HERE ###
train_steps = 50000 // BATCH_SIZE
valid_steps = 10000 // BATCH_SIZE
model.fit(train_dataset, steps_per_epoch=train_steps,   validation_data=test_dataset, validation_steps=valid_steps, epochs=40 )
### END CODE HERE ###

"""## Model evaluation

You can use this code to test your model locally before uploading to the grader. To pass, your model needs to satisfy these two requirements:

* loss must be less than 0.01
* accuracy must be greater than 0.6
"""

results = model.evaluate(test_dataset, steps=10, verbose=1)

for name, value in zip(model.metrics_names, results):
    print(f"{name}: {value}")

"""If you did some visualization like in the ungraded labs, then you might see something like the gallery below. This part is not required.

<img src="https://storage.googleapis.com/tensorflow-3-public/assets/images/autoencoder.png" width="75%" height="75%"/>

## Save the Model

Once you're satisfied with the results, you can save your model and upload it to the grader in Coursera. Please run all succeeding cells to ensure that you will have a gradable submission. Otherwise, you might get this error message:

`There was a problem grading your submission. Check stderr for more details.`

First, save the model file in your Colab workspace.
"""

# Save the model you just trained
model.save("mymodel.keras")


"""**Congratulations on completing this week's assignment!**"""